import React from 'react';
import { FormConfiguration } from '../components/Form';
import Form from '../components/Form';


const JoinForm = () => {

    const joinForm = new FormConfiguration();

    joinForm.title = "Join LESA";
    joinForm.emoji = "🤝";
    joinForm.destination = "https://api.lesauoft.com/submit/join";
    joinForm.questions = [{
        title: "What is your given name?",
        databaseKey: "given_name",
        type: "text",
        placeholder: "Enter your name",
        required: true
    }, {
        title: "What is your surname?",
        databaseKey: "surname_name",
        type: "text",
        placeholder: "Enter your surname",
        required: true
    }, {
        title: "Do you have a preferred name?",
        databaseKey: "preferred_name",
        type: "text",
        placeholder: "Enter your preferred name",
        required: false
    }, {
        title: "What is your UofT Email?",
        databaseKey: "uoft_email",
        type: "text",
        placeholder: "Enter your UofT Email",
        required: true
    }, {
        title: "What is your student number?",
        databaseKey: "student_number",
        type: "text",
        placeholder: "Enter your student number",
        required: true
    }, {
        title: "What is your status?",
        databaseKey: "student_status",
        type: "dropdown",
        placeholder: "Select your status",
        options: ["Full-Time Undergraduate", "Part-Time Undergraduate", "Graduate", "Alumni", "Faculty/Staff",  "Other"],
        required: true
    }, {
        title: "What is your faculty?",
        databaseKey: "faculty",
        type: "dropdown",
        placeholder: "Select your faculty",
        options: ["Applied Science & Engineering", "Architecture Landscape & Design", "Arts & Science", "Continuing Studies", "Dentistry", "Education", "Information", "Kinesiology", "Law", "Management", "Medicine", "Music", "Nursing", "Pharmacy", "Public Health", "Social Work", "Scarborough", "Mississauga", "Other"],
        required: true
    }, {
        title: "What is your College/Campus? (St. George for Engineering Students)",
        databaseKey: "college",
        type: "dropdown",
        placeholder: "Select your college/campus",
        options: ["Innis", "New College", "St. Michael's College", "Trinity College", "University College", "Victoria College", "Woodsworth College", "Scarborough Campus", "Mississauga Campus", "St. George", "N/A"],
        required: true
    }, {
        title: "What is your program?",
        databaseKey: "program",
        type: "text",
        placeholder: "Enter your program",
        required: true
    }, {
        title: "What is your year of study?",
        databaseKey: "year_of_study",
        type: "dropdown",
        placeholder: "Select your year of study",
        options: ["First", "Second", "Third", "PEY", "Fourth", "Graduate", "Alumni", "N/A"],
        required: true
    }, {
        title: "What is your nationality? (Canada & LATAM Countries listed first)",
        databaseKey: "country",
        type: "dropdown",
        placeholder: "Select your nationality",
        options: [
            "Canada",
            "Argentina",
            "Bolivia (Plurinational State of)",
            "Brazil",
            "Chile",
            "Colombia",
            "Costa Rica",
            "Cuba",
            "Dominican Republic (the)",
	        "Ecuador",
            "El Salvador",
            "Guatemala",
            "Honduras",
            "Mexico",
            "Nicaragua",
            "Panama",
            "Paraguay",
	        "Peru",
            "Puerto Rico",
            "Uruguay",
            "Venezuela (Bolivarian Republic of)",
	"Afghanistan",
	"Albania",
	"Algeria",
	"American Samoa",
	"Andorra",
	"Angola",
	"Anguilla",
	"Antarctica",
	"Antigua and Barbuda",
	"Armenia",
	"Aruba",
	"Australia",
	"Austria",
	"Azerbaijan",
	"Bahamas (the)",
	"Bahrain",
	"Bangladesh",
	"Barbados",
	"Belarus",
	"Belgium",
	"Belize",
	"Benin",
	"Bermuda",
	"Bhutan",
	"Bonaire, Sint Eustatius and Saba",
	"Bosnia and Herzegovina",
	"Botswana",
	"Bouvet Island",
	"British Indian Ocean Territory (the)",
	"Brunei Darussalam",
	"Bulgaria",
	"Burkina Faso",
	"Burundi",
	"Cabo Verde",
	"Cambodia",
	"Cameroon",
	"Cayman Islands (the)",
	"Central African Republic (the)",
	"Chad",
	"China",
	"Christmas Island",
	"Cocos (Keeling) Islands (the)",
	"Comoros (the)",
	"Congo (the Democratic Republic of the)",
	"Congo (the)",
	"Cook Islands (the)",
	"Croatia",
	"Curaçao",
	"Cyprus",
	"Czechia",
	"Côte d'Ivoire",
	"Denmark",
	"Djibouti",
	"Dominica",
	"Egypt",
	"Equatorial Guinea",
	"Eritrea",
	"Estonia",
	"Eswatini",
	"Ethiopia",
	"Falkland Islands (the) [Malvinas]",
	"Faroe Islands (the)",
	"Fiji",
	"Finland",
	"France",
	"French Guiana",
	"French Polynesia",
	"French Southern Territories (the)",
	"Gabon",
	"Gambia (the)",
	"Georgia",
	"Germany",
	"Ghana",
	"Gibraltar",
	"Greece",
	"Greenland",
	"Grenada",
	"Guadeloupe",
	"Guam",
	"Guatemala",
	"Guernsey",
	"Guinea",
	"Guinea-Bissau",
	"Guyana",
	"Haiti",
	"Heard Island and McDonald Islands",
	"Holy See (the)",
	"Hong Kong",
	"Hungary",
	"Iceland",
	"India",
	"Indonesia",
	"Iran (Islamic Republic of)",
	"Iraq",
	"Ireland",
	"Isle of Man",
	"Israel",
	"Italy",
	"Jamaica",
	"Japan",
	"Jersey",
	"Jordan",
	"Kazakhstan",
	"Kenya",
	"Kiribati",
	"Korea (the Democratic People's Republic of)",
	"Korea (the Republic of)",
	"Kuwait",
	"Kyrgyzstan",
	"Lao People's Democratic Republic (the)",
	"Latvia",
	"Lebanon",
	"Lesotho",
	"Liberia",
	"Libya",
	"Liechtenstein",
	"Lithuania",
	"Luxembourg",
	"Macao",
	"Madagascar",
	"Malawi",
	"Malaysia",
	"Maldives",
	"Mali",
	"Malta",
	"Marshall Islands (the)",
	"Martinique",
	"Mauritania",
	"Mauritius",
	"Mayotte",
	"Mexico",
	"Micronesia (Federated States of)",
	"Moldova (the Republic of)",
	"Monaco",
	"Mongolia",
	"Montenegro",
	"Montserrat",
	"Morocco",
	"Mozambique",
	"Myanmar",
	"Namibia",
	"Nauru",
	"Nepal",
	"Netherlands (the)",
	"New Caledonia",
	"New Zealand",
	"Niger (the)",
	"Nigeria",
	"Niue",
	"Norfolk Island",
	"Northern Mariana Islands (the)",
	"Norway",
	"Oman",
	"Pakistan",
	"Palau",
	"Palestine, State of",
	"Panama",
	"Papua New Guinea",
	"Philippines (the)",
	"Pitcairn",
	"Poland",
	"Portugal",
	"Qatar",
	"Republic of North Macedonia",
	"Romania",
	"Russian Federation (the)",
	"Rwanda",
	"Réunion",
	"Saint Barthélemy",
	"Saint Helena, Ascension and Tristan da Cunha",
	"Saint Kitts and Nevis",
	"Saint Lucia",
	"Saint Martin (French part)",
	"Saint Pierre and Miquelon",
	"Saint Vincent and the Grenadines",
	"Samoa",
	"San Marino",
	"Sao Tome and Principe",
	"Saudi Arabia",
	"Senegal",
	"Serbia",
	"Seychelles",
	"Sierra Leone",
	"Singapore",
	"Sint Maarten (Dutch part)",
	"Slovakia",
	"Slovenia",
	"Solomon Islands",
	"Somalia",
	"South Africa",
	"South Georgia and the South Sandwich Islands",
	"South Sudan",
	"Spain",
	"Sri Lanka",
	"Sudan (the)",
	"Suriname",
	"Svalbard and Jan Mayen",
	"Sweden",
	"Switzerland",
	"Syrian Arab Republic",
	"Taiwan",
	"Tajikistan",
	"Tanzania, United Republic of",
	"Thailand",
	"Timor-Leste",
	"Togo",
	"Tokelau",
	"Tonga",
	"Trinidad and Tobago",
	"Tunisia",
	"Turkey",
	"Turkmenistan",
	"Turks and Caicos Islands (the)",
	"Tuvalu",
	"Uganda",
	"Ukraine",
	"United Arab Emirates (the)",
	"United Kingdom of Great Britain and Northern Ireland (the)",
	"United States Minor Outlying Islands (the)",
	"United States of America (the)",
	"Uzbekistan",
	"Vanuatu",
	"Viet Nam",
	"Virgin Islands (British)",
	"Virgin Islands (U.S.)",
	"Wallis and Futuna",
	"Western Sahara",
	"Yemen",
	"Zambia",
	"Zimbabwe",
	"Åland Islands"],
        required: true
    }];

    return (
        <div>
            <Form formConfiguration={joinForm} infoState={false} infoError={null} defaultReturn="/join"/>
        </div>
    );
};

export default JoinForm;