name: Publish Main Branch to Server

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  NODE_VERSION: '20.16'                # set this to the node version to use

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install Depencencies
      run: |
        npm install
    - name: Build Site
      run: |
        npm run build

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: lesa-site
        path: ./build

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: lesa-site

    - name: Deploy to Namecheap
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftpes://server329.web-hosting.com
        username: ${{ secrets.FTP.USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: ftps
        port: 21098
        server-dir: /home/lesaueqw/public_html/
